"""Cookie export utilities.

Export bypass cookies in formats ready to use:
- curl command
- Python requests code
- JSON file
- Netscape cookie jar (curl --cookie-jar format)
"""

import json
from pathlib import Path
from urllib.parse import urlparse


def to_curl(url: str, cookies: dict[str, str]) -> str:
    """Generate a curl command with bypass cookies."""
    cookie_str = "; ".join(f"{k}={v}" for k, v in cookies.items())
    # Escape single quotes in cookie values for shell safety
    cookie_str = cookie_str.replace("'", "'\\''")
    return (
        f"curl '{url}' \\\n"
        f"  -b '{cookie_str}' \\\n"
        f"  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        f"AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'"
    )


def to_python_requests(url: str, cookies: dict[str, str]) -> str:
    """Generate Python requests code with bypass cookies."""
    cookies_repr = json.dumps(cookies, indent=4)
    return (
        f'import requests\n'
        f'\n'
        f'cookies = {cookies_repr}\n'
        f'\n'
        f'headers = {{\n'
        f'    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) '\
        f'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",\n'
        f'}}\n'
        f'\n'
        f'response = requests.get("{url}", cookies=cookies, headers=headers)\n'
        f'print(response.status_code)\n'
        f'print(response.text[:500])\n'
    )


def to_json(cookies: dict[str, str], filepath: str | Path | None = None) -> str:
    """Export cookies as JSON. Returns the JSON string, optionally saves to file."""
    data = json.dumps(cookies, indent=2)
    if filepath:
        Path(filepath).write_text(data, encoding="utf-8")
    return data


def to_netscape(cookies: dict[str, str], domain: str, filepath: str | Path | None = None) -> str:
    """Export cookies in Netscape cookie jar format (used by curl --cookie-jar).

    Format: domain  flag  path  secure  expiry  name  value
    """
    lines = ["# Netscape HTTP Cookie File", "# Generated by AntiBotLab", ""]

    # Clean domain
    if domain.startswith("www."):
        base_domain = domain[4:]
    else:
        base_domain = domain

    for name, value in cookies.items():
        # domain, include_subdomains, path, secure, expires, name, value
        lines.append(f".{base_domain}\tTRUE\t/\tTRUE\t0\t{name}\t{value}")

    content = "\n".join(lines) + "\n"
    if filepath:
        Path(filepath).write_text(content, encoding="utf-8")
    return content


def export_cookies(
    url: str,
    cookies: dict[str, str],
    fmt: str,
    output_dir: str | Path = ".",
) -> str:
    """Export cookies in the specified format.

    Args:
        url: The target URL.
        cookies: Dict of cookie name -> value.
        fmt: Export format — 'curl', 'python', 'json', 'all'.
        output_dir: Directory for file outputs.

    Returns:
        The exported string/code.
    """
    domain = urlparse(url).netloc
    output_dir = Path(output_dir)
    parts = []

    if fmt in ("curl", "all"):
        curl_cmd = to_curl(url, cookies)
        parts.append(f"# === CURL COMMAND ===\n{curl_cmd}")

    if fmt in ("python", "all"):
        py_code = to_python_requests(url, cookies)
        parts.append(f"# === PYTHON REQUESTS ===\n{py_code}")

    if fmt in ("json", "all"):
        json_path = output_dir / f"cookies_{domain.replace('.', '_')}.json"
        to_json(cookies, json_path)
        json_str = to_json(cookies)
        parts.append(f"# === JSON (saved to {json_path}) ===\n{json_str}")

    if fmt == "all":
        netscape_path = output_dir / f"cookies_{domain.replace('.', '_')}.txt"
        to_netscape(cookies, domain, netscape_path)
        parts.append(f"# === NETSCAPE COOKIE JAR (saved to {netscape_path}) ===")

    return "\n\n".join(parts)
